### PR TITLE
Fix print body class issue

### PR DESCRIPTION
**Pull request by amazingSurge**

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for the PR. Are you happy for this to be released under the MIT license?

**Comment by amazingSurge** [comment]
of course. Thanks for your work.

**Comment by amazingSurge** [comment]
Of course 


     Allan Jardine <notifications@github.com> 于 2015年7月20日, 星期一, 下午 8:15 写道：
   

 Thanks for the PR. Are you happy for this to be released under the MIT license?—

**Comment by DataTables** [comment]
Thanks :-)

**Pull request merged**
